server:
  port: 8080
logging:
  level:
    com.inditex: DEBUG

lombok:
  anyConstructor:
    addConstructorProperties: true

spring:
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:storedb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  sql:
    init:
      data-locations:
        - classpath:init-data.sql
      mode: ALWAYS